### ISSUE TITLE
[FEATURE]: use https for api.koinos.io

### ISSUE THREAD

**Issue by joticajulian** [koinos/koinos-jsonrpc#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

The actual api with HTTP can not be called from a website served with HTTPS. This is the error I receive:

> Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '<URL>'. This request has been blocked; the content must be served over HTTPS.

Is it possible to serve api.koinos.io using HTTPS?

**Comment by mvandeberg** [comment]
`api.koinos.io` can now be reached using HTTPS
