### ISSUE TITLE
Configure RPC Timeout

### ISSUE THREAD

**Issue by mvandeberg** [koinos/koinos-jsonrpc#4]
The RPC timeout is currently a constant. It should be configurable.

**Comment by naftalimurgor** [comment]
Hey @mvandeberg 
I figured the only way to configure RPC time out is to be add it to the yaml config with a senisble default as `timeout` option.
Let me know what you think
 Thank you

**Comment by naftalimurgor** [comment]
Hey @mvandeberg
I think to configure RPC timeout, it would desirable to add timeout to the yaml configuration with a  default  option.
Let me know what you think
Thank you

**Comment by sgerbino** [comment]
Implemented under #43.
